disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "images/logo.svg"
description = "My personal knowledge base"
copyright = "Copyright © 2026 Osvaldo Margato"